// export const metadata = {
//   title: 'Home | Travelmoon',
//   description: 'Generated by create next app',
// }

export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className='bg-gray'>
                {children}
            </body>
        </html>
    )
}
